---
- name: Remove Jenkins
  hosts: localhost
  become: true

  tasks:
    - name: Delete Apt Key
      ansible.builtin.apt_key:
        id: 62A9756BFD780C377CF24BA8FCEF32E745F2C3D5
        state: absent
    - name: Remove jenkins repo
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        filename: jenkins
        state: absent
    - name: Ensure Jenkins is stopped and disabled
      ansible.builtin.systemd:
        name: jenkins
        enabled: no
        state: stopped
    - name: Remove Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: absent
